### Building Intuition about NN

In [40]:
import numpy as np

In [45]:
X = np.array(([3,5],[5,1],[10,2]),dtype = float) # two features, hours studies and hours slept
y = np.array(([75],[82],[93]),dtype = float) # the mark the student got


In [46]:
# let's look at the features matrix
X

array([[ 3.,  5.],
       [ 5.,  1.],
       [10.,  2.]])

In [47]:
X.shape

(3, 2)

In [48]:
# and the response variable
y

array([[75.],
       [82.],
       [93.]])

In [49]:
y.shape

(3, 1)

In [50]:
# step 1, scaling the data, and since all the values are positives then we can just devide by the max

X = X/np.max(X, axis = 0)
y = y/100

In [51]:
X

array([[0.3, 1. ],
       [0.5, 0.2],
       [1. , 0.4]])

In [52]:
y

array([[0.75],
       [0.82],
       [0.93]])

In [78]:
# well I again got the correct answer, I should get some time to think about this mistery?


In [91]:
class NN_model:
    def __init__(self):
        
        # here we will define the size of the layer as the number of the neurons/units in each layer
        np.random.seed(500)
        self.input_layer_size = 2
        self.hidden_layer_size = 3
        self.output_layer_sizer = 1
        # weights
        
        # note that the weight matrix shape deponds only on the size of layers and not on the number of example, we only need X[1] shape and not X[0]     
        self.w1 = np.random.rand(self.input_layer_size,self.hidden_layer_size)
        self.w2 = np.random.rand(self.hidden_layer_size,self.output_layer_sizer)
        

    
    def sigmoid(self,z):
        return 1/(1+np.exp(-z))

    def sigmoid_grad(self,z):
        return self.sigmoid(z) * (1-self.sigmoid(z))
        
        
        
        
    def forward(self,X):
        """
        moving the data through the network, here we will pass the inputs X1,X2,... as matrix X instead of inividuals units 
        """
        
        # we will name the hidden layers by the letter Z, since the first hidden layer is also the second layer in the nn then we will start with z2
        
        z2 = X@self.w1
        # we apply activation function
        print('z2')
        print(z2)
        
        a2 = self.sigmoid(z2)  
        print('a2')
        print(a2)
        
        z3 = a2@self.w2
        print('z3')
        print(z3)
        
        a3 = self.sigmoid(z3)
        
        # since a3 is also y_hat then
        
        y_hat = a3
        

        
        return y_hat
   

In [92]:
# let's test the forward function for now

In [93]:
lm = NN_model()
lm.forward(X)

z2
[[0.76731279 0.10362572 0.59240254]
 [0.45868155 0.04788062 0.41178961]
 [0.9173631  0.09576124 0.82357922]]
a2
[[0.68293931 0.52588327 0.64391621]
 [0.61270136 0.51196787 0.60151692]
 [0.71450451 0.52392203 0.69499558]]
z3
[[0.7345827 ]
 [0.6805321 ]
 [0.76710807]]


array([[0.67581011],
       [0.66385745],
       [0.68289498]])

In [87]:
# why all the predictions are the same

In [ ]:
class NN_model:
    def __init__(self):
        
        # here we will define the size of the layer as the number of the neurons/units in each layer
        self.input_layer_size = 2 # we need to include those in the input of the functions as parameterss
        self.hidden_layer_size = 3
        self.output_layer_sizer = 1
        
        
        # weights
        
        # note that the weight matrix shape deponds only on the size of layers and not on the number of example, we only need X[1] shape and not X[0]     
        self.w1 = np.random.rand(self.input_layer_size,self.hidden_layer_size)
        self.w2 = np.random.rand(self.hidden_layer_size,self.output_layer_sizer)
        

    
    def sigmoid(self,z):
        return 1/(1+np.exp(-z))

    def sigmoid_grad(self,z):
        return self.sigmoid(z) * (1-self.sigmoid(z))
        
        
        
        
    def forward(self,X):
        """
        moving the data through the network, here we will pass the inputs X1,X2,... as matrix X instead of inividuals units 
        """
        
        # we will name the hidden layers by the letter Z, since the first hidden layer is also the second layer in the nn then we will start with z2
        
        z2 = X@self.w1
        # we apply activation function
        
        a2 = self.sigmoid(z2)
        
        z3 = a2@self.w2
        
        a3 = self.sigmoid(z3)
        
        # 
        
        y_hat = a3
        
        return y_hat
        
        
        
    
    
 
    
    
    def calc_loss(self,X,y,w1,w2 ,loss_measure = 'MSE'):
        
        
        """
        Calculating the loss or the deviation of the results we got from the model compared with the real values. The first step is to calculate the X@w which represents the results we got from
        the model. The second step is to evaulate the loss which can be done through a loss function that we define. for example here we define two ways to caculate the loss either using MAE, in
        which we first calculate the absolute difference between each predicted and true value and then we calucalte the mean. or using the MSW, in which we calculate the abolute difference between
        true and preidcted value, square it and then find the average. The loss we then be returned.
        
        """    
        losses = []
        
        # the first layer in the model, will take the inputs X, which has two units x1 and x2 and produce z1, z1 will have two units, z1_1, and z2_2
        z1 = X@w1
        print('z1')
        print(z1)
        # the output layer
        y_predicted= z1@w2        
        #y_predicted = self.sigmoid(z2)
        print('y_predicted',y_predicted)
        #print('grad', self.sigmoid(z) * (1-self.sigmoid(z)))
        
        
        
        
        if loss_measure == 'MSE':
            loss = (y - y_predicted)**2
        elif loss_measure == 'MAE':
            loss= abs(y - y_predicted)

        #print('the true value = ',y)
        #print('the predicted value = ',y_predicted)
        losses.append(loss)
        total_loss = np.mean(losses)
        #print('the total loss =', total_loss )
        return total_loss
      

    def diff(self,w,X,y,loss_measure,diff_type = 'Analytical'):
        """
        given a function f(x) and a point w, calculate th f'(x)
        
        """
        dldw = np.ones([X.shape[1],1])
        h = 0.005  
        
        if diff_type =='Numerical':
            # calculate the derivitives dl/dw using limits
            for i in range(len(w)):
                print('i',i)
                # f(w)
                loss_w = self.calc_loss(X,y,w,loss_measure = loss_measure)
                # we will choose the margin that we will accept as 0.5
                # f(w+h)
                w[i] = w[i] + h      
                loss_w_plus_h = self.calc_loss(X,y,w,loss_measure = loss_measure)
                # dldw = f(w+h) - f(w)/h
                dldw[i] = (loss_w_plus_h- loss_w)/h
                print('dldw using numerical solution')
                print(dldw)
        elif diff_type == 'Analytical':
            # calculate the derivitves dl/dw using calculus
            # l = (X.w - y)**2
            # dl/dw = 2*(X.w - y)@X = 2*X@()
            
            z = X@w
            
            print('sigmpod_grad = ',self.sigmoid_grad(z))
            
            dldw = 2*X@(z - y)#*self.sigmoid_grad(z)
            print('dldw using analytical solution')
            print(dldw)
        return dldw 
    
    def train(self,X,y,loss_measure = 'MAE', lr = 0.07, diff_type = 'Analytical'):
        """
        training of the model is done by evaluting loss and updating the weights
        """
        # initilization
        np.random.seed(50)
        w1 = np.random.rand(X.shape[1],2)
        w2 = np.random.rand(X.shape[1],1)
        # intialization. I am changing this manually
        #w[0] = 
        #w[1] = 3.5
        #print('initial weights')
        #print(w1)    
        # updating the weight     
        #lr =0.07
        
        for i in range(30):
            print('step =',i)
            
            # forward pass is essentially the process of calculting the loss given the data and the weight, for the loss we need to calculate a predicted value
            # calculate the loss at the current weights
            loss_w = self.calc_loss(X,y,w1,w2)
            print('loss is now',loss_w)
            # stoping condition, note that we don't require the loss is to be exactly zero but close enough
            if loss_w <= 0.08 :
                self.w = w
                print('final w = ',self.w)
                return self.w
            
            # updating the weight. 
            elif loss_w > 0.08 :
                # the backpropagation is essentially the calculation of the partially derivives using chain rules. since we have only one layer at this time we will just calculate the dldw
                #First at that particular point we calculate dldw 
                
                
                # dldw1 = dl/dz*dz/dw1
                #dl/dz =2(x@w-y), l = (z-y)**2
                
                #dz/dw = X>>>>>>>>>>>>>why: becauaw z =X@w
         
                # the new w is w2
                
                z1 = X@w1 # this is the new x
                dldw2 =  2*z1@(z1@w2 - y)#self.diff(w1,X,y,loss_measure, diff_type)
                
                print('x')
                print(X)
                print('w2')
                print(w2)
                
#                 h= X@w2
#                 print(h)
#                 h2 = z1@w2  -y
#                 print(h2)
                
#                 dldw1 = 2*(h)@(h2)
                
                
#                 
                
                dldw1 = 2*w2*(z1@w2-y)@X
                               
                               
                # dl/dw1
                print('dldw1,2')
                print(dldw1)
                print(dldw2)
                
               # print(w2)
                #dldw2 = self.diff(w2,X,y,loss_measure, diff_type)
                # Now we update the weight
                w1 = w1 -lr*dldw1
                w2 = w2 -lr*dldw2
                
                print('w1')
                print(w1)  
                                
                print('w2')
                print(w2) 
                
    def predict(self,X_new):
        """
        Given a new data, the model will be using the weights stored in the self.w to produce a prediction
        """
        predicted_y = X_new@self.w
        
