### Array Multiplication

In [28]:
import numpy as np

In [71]:
# let's use numpy for matrix multiplication

In [54]:
# row array
X = np.array([1,2,3,4,5]).reshape(1,5)
X


array([[1, 2, 3, 4, 5]])

In [55]:
#
X.shape

(1, 5)

In [56]:
# we want the output to be either 0 or 1

In [57]:
# ok, we need to learn about the dot product, so we can peformr X.w

In [61]:
# X is 5 * 1 and the output is 2 *1 so we need the w to be 2*5

w = np.array([
    [ 0.1, 0.1, 0.1,0.1,0.1],
    [0.1,0.1,0.1,0.1,0.1]

])

In [66]:
w = w.reshape(5,2)

In [67]:
w

array([[0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1]])

In [70]:
X@w

array([[1.5, 1.5]])

In [ ]:
# input layer, 5 nodes        layer 1, 2 nodes

#
#                    #
#
#                    #
#

In [73]:
# let's make up a simple example to see if the NN can actually learn from examples


# y X1 + X2 + X3 + X4 + X5

# examples
X = np.array([[1,1,1,1,1],
             [2,1,2,2,2],
            [3,1,3,3,3],
            [3,2,3,3,3],
            [3,3,3,3,3],
            [3,4,3,3,3],
            [3,5,3,3,3],
            [3,6,3,3,3],
            [3,7,3,3,3],
            [3,8,3,3,3]
             ])


In [111]:
X.shape

(10, 5)

In [110]:
y = np.array([5,9,13,14,15,16,17,18,19,20])
y.shape

(10,)

In [162]:
class linear_model:
    def __init__(self):
        pass

    def train(self,X,y):
        w = np.ones([X.shape[1],1])
        w[0] = 0.2
        losses = []
        y_predicted = np.zeros(len(X))
        for i in range(len(X)):
            y_predicted[i] = X[i]@w
            loss = y[i] - y_predicted[i]
            
            print('the true value = ',y[i])
            print('the predicted value = ',y_predicted[i])
            losses.append(loss)
        total_loss = np.sum(losses)
        print('the total loss =', total_loss )
        

In [163]:
lm = linear_model()

In [164]:
lm.train(X,y)

the true value =  5
the predicted value =  4.2
the true value =  9
the predicted value =  7.4
the true value =  13
the predicted value =  10.6
the true value =  14
the predicted value =  11.6
the true value =  15
the predicted value =  12.6
the true value =  16
the predicted value =  13.6
the true value =  17
the predicted value =  14.6
the true value =  18
the predicted value =  15.6
the true value =  19
the predicted value =  16.6
the true value =  20
the predicted value =  17.6
the total loss = 21.599999999999998


In [158]:
X[0]

array([1, 1, 1, 1, 1])

In [139]:
# note that we used the correct w for this case and hence we have loss of zero, let's change ws

In [148]:
w = np.ones([X.shape[1],1])

In [150]:
w[0] = 0.2

In [151]:
w

array([[0.2],
       [1. ],
       [1. ],
       [1. ],
       [1. ]])