### Array Multiplication

In [1]:
import numpy as np

In [2]:
# let's use numpy for matrix multiplication

In [3]:
# row array
X = np.array([1,2,3,4,5]).reshape(1,5)
X


array([[1, 2, 3, 4, 5]])

In [4]:
#
X.shape

(1, 5)

In [5]:
# we want the output to be either 0 or 1

In [6]:
# ok, we need to learn about the dot product, so we can peformr X.w

In [7]:
# X is 5 * 1 and the output is 2 *1 so we need the w to be 2*5

w = np.array([
    [ 0.1, 0.1, 0.1,0.1,0.1],
    [0.1,0.1,0.1,0.1,0.1]

])

In [8]:
w = w.reshape(5,2)

In [9]:
w

array([[0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1]])

In [10]:
X@w

array([[1.5, 1.5]])

In [11]:
# input layer, 5 nodes        layer 1, 2 nodes

#
#                    #
#
#                    #
#

In [12]:
# let's make up a simple example to see if the NN can actually learn from examples


# y X1 + X2 + X3 + X4 + X5

# examples
X = np.array([[1,1,1,1,1],
             [2,1,2,2,2],
            [3,1,3,3,3],
            [3,2,3,3,3],
            [3,3,3,3,3],
            [3,4,3,3,3],
            [3,5,3,3,3],
            [3,6,3,3,3],
            [3,7,3,3,3],
            [3,8,3,3,3]
             ])


In [13]:
X.shape

(10, 5)

In [14]:
y = np.array([5,9,13,14,15,16,17,18,19,20])
y.shape

(10,)

### Train function

In [15]:
class linear_model:
    def __init__(self):
        pass

    def train(self,X,y):
        # create the weight vectorr
        w = np.ones([X.shape[1],1])
        losses = []
        y_predicted = np.zeros(len(X))
        for i in range(len(X)):
            y_predicted[i] = X[i]@w
            loss = y[i] - y_predicted[i]
            
            print('the true value = ',y[i])
            print('the predicted value = ',y_predicted[i])
            losses.append(loss)
        total_loss = np.sum(losses)
        print('the total loss =', total_loss )
        

In [16]:
lm = linear_model()

In [17]:
lm.train(X,y)

the true value =  5
the predicted value =  5.0
the true value =  9
the predicted value =  9.0
the true value =  13
the predicted value =  13.0
the true value =  14
the predicted value =  14.0
the true value =  15
the predicted value =  15.0
the true value =  16
the predicted value =  16.0
the true value =  17
the predicted value =  17.0
the true value =  18
the predicted value =  18.0
the true value =  19
the predicted value =  19.0
the true value =  20
the predicted value =  20.0
the total loss = 0.0


In [18]:
X[0]

array([1, 1, 1, 1, 1])

In [19]:
# note that we used the correct w for this case and hence we have loss of zero, let's change ws

In [23]:
class linear_model:
    def __init__(self):
        pass

    def train(self,X,y):
        w = np.ones([X.shape[1],1])
        w[0] = 0.2
        losses = []
        y_predicted = np.zeros(len(X))
        for i in range(len(X)):
            y_predicted[i] = X[i]@w
            loss_at_w = y[i] - y_predicted[i]
            loss_at_w_plus_h = y[i] - y_predicted[i]
            
            print('the true value = ',y[i])
            print('the predicted value = ',y_predicted[i])
            losses.append(loss_at_w )
        total_loss = np.sum(losses)
        print('the total loss =', total_loss)
              
        
        

In [24]:
lm = linear_model()

In [25]:
lm.train(X,y)

the true value =  5
the predicted value =  4.2
the true value =  9
the predicted value =  7.4
the true value =  13
the predicted value =  10.6
the true value =  14
the predicted value =  11.6
the true value =  15
the predicted value =  12.6
the true value =  16
the predicted value =  13.6
the true value =  17
the predicted value =  14.6
the true value =  18
the predicted value =  15.6
the true value =  19
the predicted value =  16.6
the true value =  20
the predicted value =  17.6
the total loss = 21.599999999999998


In [26]:
# as you can see here, the loss is no longer 0.

In [27]:
# it is obvious that we need to keep tweeking ws until we get the minium loss

### now comes the calculs part, first we know that we can write the loss as a function of ws

- L = f(w)
- dl/dw = f'(w) = (f(w+h) - f(w))/h

new_w = old+w - step_size* dl/dw

In [28]:
 #ok, I need to update w which is a vector of shape (x[1],1)
        # any change in w, for example if we change w[0], the vector y will change completely, not only y[0] as we dicussed before.
        # now as we said we want to change w by tweeking it a little bit, by adding dw, i.e adding a vector that will be similar in length to w
              
        # for example :
              # w = [1               df/dw = [0.10                                                        [1.2
              #      2                     0.04            > new w will be old_w _ step_size*dw.     >. 2.08         note that here we assumed step*size to be 2
               #     3]                    0.03]                                                         2.06
        
        # let's calculate dl/dw
        # but this will involve calculating the loss twice, one at and then at w + h
        # let's make a function of calculating the loss
        

## Using a simple model to solve the equation 3X = 6

In [171]:
class linear_model:
    def __init__(self):
        pass
    
    def calc_loss(self,X,y,w):
       
        losses = []
        y_predicted = np.zeros(len(X))
       
        for i in range(len(X)):
            y_predicted[i] = X[i]@w
            loss= y[i] - y_predicted[i]
            
            print('the true value = ',y[i])
            print('the predicted value = ',y_predicted[i])
            losses.append(loss)
        total_loss = np.sum(losses)
        print('the total loss =', total_loss )
        return total_loss
      


    def train(self,X,y):
        w = np.ones([X.shape[1],1])
        w[0] = 5
        
        for i in range(len(w)):
            loss_w = self.calc_loss(X,y,w)
            
            # the case when the loss is positive, in this case we need to decrease w
            
            # we will choose the margin that we will accept as 0.5
            
            if abs(loss_w)> 0:
                # since the equation is 3x =6 , then dw/dl = 3
                dldw = 3
            elif abs(loss_w)< 0:
                dldw = -3
                # we will make the the learning rate is 0.5
            lr =1
            w[0]= w[0] -lr*dldw
            loss_w_dash= self.calc_loss(X,y,w)
            print(loss_w_dash - loss_w)
            loss_w = loss_w_dash

            
            self.w = w
            print(self.w)
        
    def predict(self,X_new):
        predicted_y = X_new@self.w
        
        return predicted_y

In [172]:
X = np.array([3]).reshape(1,1)
y = np.array([6]).reshape(1,1)

In [173]:
X.shape

(1, 1)

In [174]:
w = np.ones([1,1])

In [175]:
X@w

array([[3.]])

In [176]:
lm = linear_model()

In [177]:
lm.train(X,y)

the true value =  [6]
the predicted value =  15.0
the total loss = -9.0
the true value =  [6]
the predicted value =  6.0
the total loss = 0.0
9.0
[[2.]]


In [178]:
# so essentially the equation we have is

# 2*X, this is our model, because this is basically what got us 6
# let's see what if we try a new X, say for example 4, we expect the new y to be 8

In [179]:
X_new = np.array([4])

In [180]:
y = lm.predict(X_new)

In [181]:
y

array([8.])

### sensetivity to learning rate