### Array Multiplication

In [28]:
import numpy as np

In [71]:
# let's use numpy for matrix multiplication

In [54]:
# row array
X = np.array([1,2,3,4,5]).reshape(1,5)
X


array([[1, 2, 3, 4, 5]])

In [55]:
#
X.shape

(1, 5)

In [56]:
# we want the output to be either 0 or 1

In [57]:
# ok, we need to learn about the dot product, so we can peformr X.w

In [61]:
# X is 5 * 1 and the output is 2 *1 so we need the w to be 2*5

w = np.array([
    [ 0.1, 0.1, 0.1,0.1,0.1],
    [0.1,0.1,0.1,0.1,0.1]

])

In [66]:
w = w.reshape(5,2)

In [67]:
w

array([[0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1]])

In [70]:
X@w

array([[1.5, 1.5]])

In [ ]:
# input layer, 5 nodes        layer 1, 2 nodes

#
#                    #
#
#                    #
#

In [73]:
# let's make up a simple example to see if the NN can actually learn from examples


# y X1 + X2 + X3 + X4 + X5

# examples
X = np.array([[1,1,1,1,1],
             [2,1,2,2,2],
            [3,1,3,3,3],
            [3,2,3,3,3],
            [3,3,3,3,3],
            [3,4,3,3,3],
            [3,5,3,3,3],
            [3,6,3,3,3],
            [3,7,3,3,3],
            [3,8,3,3,3]
             ])


In [111]:
X.shape

(10, 5)

In [110]:
y = np.array([5,9,13,14,15,16,17,18,19,20])
y.shape

(10,)

In [165]:
class linear_model:
    def __init__(self):
        pass

    def train(self,X,y):
        w = np.ones([X.shape[1],1])
        losses = []
        y_predicted = np.zeros(len(X))
        for i in range(len(X)):
            y_predicted[i] = X[i]@w
            loss = y[i] - y_predicted[i]
            
            print('the true value = ',y[i])
            print('the predicted value = ',y_predicted[i])
            losses.append(loss)
        total_loss = np.sum(losses)
        print('the total loss =', total_loss )
        

In [166]:
lm = linear_model()

In [167]:
lm.train(X,y)

the true value =  5
the predicted value =  5.0
the true value =  9
the predicted value =  9.0
the true value =  13
the predicted value =  13.0
the true value =  14
the predicted value =  14.0
the true value =  15
the predicted value =  15.0
the true value =  16
the predicted value =  16.0
the true value =  17
the predicted value =  17.0
the true value =  18
the predicted value =  18.0
the true value =  19
the predicted value =  19.0
the true value =  20
the predicted value =  20.0
the total loss = 0.0


In [168]:
X[0]

array([1, 1, 1, 1, 1])

In [139]:
# note that we used the correct w for this case and hence we have loss of zero, let's change ws

In [169]:
class linear_model:
    def __init__(self):
        pass

    def train(self,X,y):
        w = np.ones([X.shape[1],1])
        w[0] = 0.2
        losses = []
        y_predicted = np.zeros(len(X))
        for i in range(len(X)):
            y_predicted[i] = X[i]@w
            loss_at_w = y[i] - y_predicted[i]
            loss_at_w_plus_h = y[i] - y_predicted[i]
            
            print('the true value = ',y[i])
            print('the predicted value = ',y_predicted[i])
            losses.append(loss_at_w )
        total_loss = np.sum(losses)
        print('the total loss =', total_loss 
              
        
        

In [170]:
lm = linear_model()

In [171]:
lm.train(X,y)

the true value =  5
the predicted value =  4.2
the true value =  9
the predicted value =  7.4
the true value =  13
the predicted value =  10.6
the true value =  14
the predicted value =  11.6
the true value =  15
the predicted value =  12.6
the true value =  16
the predicted value =  13.6
the true value =  17
the predicted value =  14.6
the true value =  18
the predicted value =  15.6
the true value =  19
the predicted value =  16.6
the true value =  20
the predicted value =  17.6
the total loss = 21.599999999999998


In [172]:
# as you can see here, the loss is no longer 0.

In [173]:
# it is obvious that we need to keep tweeking ws until we get the minium loss

### now comes the calculs part, first we know that we can write the loss as a function of ws

- L = f(w)
- dl/dw = f'(w) = (f(w+h) - f(w))/h

new_w = old+w - step_size* dl/dw

In [174]:
 #ok, I need to update w which is a vector of shape (x[1],1)
        # any change in w, for example if we change w[0], the vector y will change completely, not only y[0] as we dicussed before.
        # now as we said we want to change w by tweeking it a little bit, by adding dw, i.e adding a vector that will be similar in length to w
              
        # for example :
              # w = [1               df/dw = [0.10                                                        [1.2
              #      2                     0.04            > new w will be old_w _ step_size*dw.     >. 2.08         note that here we assumed step*size to be 2
               #     3]                    0.03]                                                         2.06
        
        # let's calculate dl/dw
        # but this will involve calculating the loss twice, one at and then at w + h
        # let's make a function of calculating the loss
        

In [208]:
class linear_model:
    def __init__(self):
        pass
    
    def calc_loss(self,X,y,w):
       
        losses = []
        y_predicted = np.zeros(len(X))
       
        for i in range(len(X)):
            y_predicted[i] = X[i]@w
            loss= y[i] - y_predicted[i]
            
            print('the true value = ',y[i])
            print('the predicted value = ',y_predicted[i])
            losses.append(loss)
        total_loss = np.sum(losses)
        print('the total loss =', total_loss )
        return total_loss
      


    def train(self,X,y):
        w = np.ones([X.shape[1],1])
        w[0] = 0.2
        loss = self.calc_loss(X,y,w)
        
        dwdl = np.array([x*0.001 for x in w]).reshape(X.shape[1],1)
            
        if loss > 2 :
            
            fw = loss

            w = w - 0.0002*dwdl
            
            fw_h = self.calc_loss(X,y,w)

            dwdl = (fw_h - fw)/0.001
            print('dwdl',dwdl)
            
            loss = self.calc_loss(X,y,w)   
        else :
            return loss

In [209]:
lm = linear_model()

In [210]:
lm.train(X,y)

the true value =  5
the predicted value =  4.2
the true value =  9
the predicted value =  7.4
the true value =  13
the predicted value =  10.6
the true value =  14
the predicted value =  11.6
the true value =  15
the predicted value =  12.6
the true value =  16
the predicted value =  13.6
the true value =  17
the predicted value =  14.6
the true value =  18
the predicted value =  15.6
the true value =  19
the predicted value =  16.6
the true value =  20
the predicted value =  17.6
the total loss = 21.599999999999998
the true value =  5
the predicted value =  4.199991600000001
the true value =  9
the predicted value =  7.399985200000001
the true value =  13
the predicted value =  10.5999788
the true value =  14
the predicted value =  11.5999768
the true value =  15
the predicted value =  12.5999748
the true value =  16
the predicted value =  13.5999728
the true value =  17
the predicted value =  14.599970800000001
the true value =  18
the predicted value =  15.599968800000001
the true v

In [ ]:
# I think I must find a way to do this cacluation of gradient across all dimensins