### Building Intuition about NN

In [775]:
import numpy as np

In [776]:
# The best approach to get an intuision for building NN is to start from scratch, and I will start with matrix mutiplication, as it's the foundational knowledge

let's start with equations, after all linear algebra was built to solve equations

X.w = y



In [777]:
# what does this eqaution tells us, that the dot product of feature matrix X and weight vector w will get us y. But the shape matters for matrix multiplication as we will see


In [778]:
# let's creat our feature matrix, we will have a data with only one example and 5 features.

In [779]:
X = np.array([10,12,5,3,-5]).reshape(1,5)
X


array([[10, 12,  5,  3, -5]])

we have come to know that there is a dependent variable y, that is linearly dependent on those features. That means if we take the right mix of theres features in X we will get y.
 of course the million dollar question is that what is the right mix. Let's say we the right mix of feature X1 is w1 and from featureX2 is w2 etc. Now, we will get the following equation

X1.w1 + X2.w2 + ...... Xn.wn = y

we can write the above equation in a compact form in the following form:

X.w = y

Now, to write this equation in the matrix form, we need to know the rules of matrix multiplication



- the rows of w has to be the same as the columns of X
- so if X shape is 1,5 then w needs to be 5x, so we can have any numbe of columns but the rows have to be 5. The resuled matrix will take the shape of (rows of X , columns of w)
- why is this important, well, since the number of rows in X is the numbe of example, observations in the data does not affect. We can have the same shape of w for any number of observations. 
- On the other hands, w is affected by the number of features, of course becuase each w is connected with aparticualr feature.
- Now when it comes the resulted y, of coursee we need one y for each observation, and therefore the numbe of rows in y is the same as number of observation. Now let's say we don't have one output
- I mean we have y1 and y2, we will face this in multi-classificaiton and also in NN when w have a layer with more than one unit. Here th columns of y will increase, and guess who will increase the numbe of columns to accomodate this, yes that's right. That's the NN

In [780]:
# ok, we need to learn about the dot product, so we can peformr X.w

In [781]:
# X is 5 * 1 and the output is 2 *1 so we need the w to be 2*5

w = np.array([
    [ 0.1, 0.1, 0.1,0.1,0.1],
    [0.1,0.1,0.1,0.1,0.1]

])

In [782]:
w = w.reshape(5,2)

In [783]:
w

array([[0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1]])

In [784]:
X@w

array([[2.5, 2.5]])

In [785]:
# input layer, 5 nodes        layer 1, 2 nodes

#
#                    #
#
#                    #
#

In [786]:
# let's make up a simple example to see if the NN can actually learn from examples


# y X1 + X2 + X3 + X4 + X5

# examples
X = np.array([[1,1,1,1,1],
             [2,1,2,2,2],
            [3,1,3,3,3],
            [3,2,3,3,3],
            [3,3,3,3,3],
            [3,4,3,3,3],
            [3,5,3,3,3],
            [3,6,3,3,3],
            [3,7,3,3,3],
            [3,8,3,3,3]
             ])


In [787]:
X.shape

(10, 5)

In [788]:
y = np.array([5,9,13,14,15,16,17,18,19,20])
y.shape

(10,)

### Train function

In [789]:
class linear_model:
    def __init__(self):
        pass

    def train(self,X,y):
        # create the weight vectorr
        w = np.ones([X.shape[1],1])
        losses = []
        y_predicted = np.zeros(len(X))
        for i in range(len(X)):
            y_predicted[i] = X[i]@w
            loss = y[i] - y_predicted[i]
            
            print('the true value = ',y[i])
            print('the predicted value = ',y_predicted[i])
            losses.append(loss)
        total_loss = np.sum(losses)
        print('the total loss =', total_loss )
        

In [790]:
lm = linear_model()

In [791]:
lm.train(X,y)

the true value =  5
the predicted value =  5.0
the true value =  9
the predicted value =  9.0
the true value =  13
the predicted value =  13.0
the true value =  14
the predicted value =  14.0
the true value =  15
the predicted value =  15.0
the true value =  16
the predicted value =  16.0
the true value =  17
the predicted value =  17.0
the true value =  18
the predicted value =  18.0
the true value =  19
the predicted value =  19.0
the true value =  20
the predicted value =  20.0
the total loss = 0.0


In [792]:
X[0]

array([1, 1, 1, 1, 1])

In [793]:
# note that we used the correct w for this case and hence we have loss of zero, let's change ws

In [794]:
class linear_model:
    def __init__(self):
        pass

    def train(self,X,y):
        w = np.ones([X.shape[1],1])
        w[0] = 0.2
        losses = []
        y_predicted = np.zeros(len(X))
        for i in range(len(X)):
            y_predicted[i] = X[i]@w
            loss_at_w = y[i] - y_predicted[i]
            loss_at_w_plus_h = y[i] - y_predicted[i]
            
            print('the true value = ',y[i])
            print('the predicted value = ',y_predicted[i])
            losses.append(loss_at_w )
        total_loss = np.sum(losses)
        print('the total loss =', total_loss)
              
        
        

In [795]:
lm = linear_model()

In [796]:
lm.train(X,y)

the true value =  5
the predicted value =  4.2
the true value =  9
the predicted value =  7.4
the true value =  13
the predicted value =  10.6
the true value =  14
the predicted value =  11.6
the true value =  15
the predicted value =  12.6
the true value =  16
the predicted value =  13.6
the true value =  17
the predicted value =  14.6
the true value =  18
the predicted value =  15.6
the true value =  19
the predicted value =  16.6
the true value =  20
the predicted value =  17.6
the total loss = 21.599999999999998


In [797]:
# as you can see here, the loss is no longer 0.

In [798]:
# it is obvious that we need to keep tweeking ws until we get the minium loss

### now comes the calculs part, first we know that we can write the loss as a function of ws

- L = f(w)
- dl/dw = f'(w) = (f(w+h) - f(w))/h

new_w = old+w - step_size* dl/dw

In [799]:
 #ok, I need to update w which is a vector of shape (x[1],1)
        # any change in w, for example if we change w[0], the vector y will change completely, not only y[0] as we dicussed before.
        # now as we said we want to change w by tweeking it a little bit, by adding dw, i.e adding a vector that will be similar in length to w
              
        # for example :
              # w = [1               df/dw = [0.10                                                        [1.2
              #      2                     0.04            > new w will be old_w _ step_size*dw.     >. 2.08         note that here we assumed step*size to be 2
               #     3]                    0.03]                                                         2.06
        
        # let's calculate dl/dw
        # but this will involve calculating the loss twice, one at and then at w + h
        # let's make a function of calculating the loss
        

## Using a simple model to solve the equation 3X = 6

In [800]:
class linear_model:
    def __init__(self):
        pass
    
    def calc_loss(self,X,y,w):
       
        losses = []
        y_predicted = np.zeros(len(X))
       
        
        y_predicted = X@w
        loss= y - y_predicted
            
        print('the true value = ',y)
        print('the predicted value = ',y_predicted)
        losses.append(loss)
        total_loss = np.sum(losses)
        print('the total loss =', total_loss )
        return total_loss
      


    def train(self,X,y):
        w = np.ones([X.shape[1],1])
        w[0] = 5
        
        for i in range(len(w)):
            loss_w = self.calc_loss(X,y,w)
            
            # the case when the loss is positive, in this case we need to decrease w
            
            # we will choose the margin that we will accept as 0.5
            
            if abs(loss_w)> 0:
                # since the equation is 3x =6 , then dw/dl = 3
                dldw = 3
            elif abs(loss_w)< 0:
                dldw = -3
                # we will make the the learning rate is 0.5
            lr =1
            w[0]= w[0] -lr*dldw
            loss_w_dash= self.calc_loss(X,y,w)
            print(loss_w_dash - loss_w)
            loss_w = loss_w_dash

            
            self.w = w
            print(self.w)
        
    def predict(self,X_new):
        predicted_y = X_new@self.w
        
        return predicted_y

In [801]:
X = np.array([3]).reshape(1,1)
y = np.array([6]).reshape(1,1)

In [802]:
X.shape

(1, 1)

In [803]:
w = np.ones([1,1])

In [804]:
X@w

array([[3.]])

In [805]:
lm = linear_model()

In [806]:
lm.train(X,y)

the true value =  [[6]]
the predicted value =  [[15.]]
the total loss = -9.0
the true value =  [[6]]
the predicted value =  [[6.]]
the total loss = 0.0
9.0
[[2.]]


In [807]:
# so essentially the equation we have is

# 2*X, this is our model, because this is basically what got us 6
# let's see what if we try a new X, say for example 4, we expect the new y to be 8

In [808]:
X_new = np.array([4])

In [809]:
y = lm.predict(X_new)

In [810]:
y

array([8.])

### let's now try equations for 2 variables


- X1 = 2
- X2 = 3

- 2X1 + X2 = 7
- 3X1 - X2 = 3

> this is the equivelant of having 2 examples


In [811]:
X = np.array([[2,1],
             [3,-1]])
X

array([[ 2,  1],
       [ 3, -1]])

In [812]:
y = np.array([7,3]).reshape(2,1)
y

array([[7],
       [3]])

In [813]:
class linear_model:
    def __init__(self):
        pass
    
    def calc_loss(self,X,y,w):
       
        losses = []
        y_predicted = np.zeros(len(X))
       
        
        y_predicted = X@w
        loss= y - y_predicted

        print('the true value = ',y)
        print('the predicted value = ',y_predicted)
        losses.append(loss)
        total_loss = np.sum(losses)
        print('the total loss =', total_loss )
        return total_loss
      


    def train(self,X,y):
        w = np.ones([X.shape[1],1])
        w[0] = 5
        w[1] = 3
        
        loss_w = self.calc_loss(X,y,w)
        while abs(loss_w) > 1:
            for i in range(len(w)):
                loss_w = self.calc_loss(X,y,w)

                # the case when the loss is positive, in this case we need to decrease w

                # we will choose the margin that we will accept as 0.5

                if abs(loss_w)> 0:
                    # since the equation is 3x =6 , then dw/dl = 3
                    dldw = 1
                elif abs(loss_w)< 0:
                    dldw = -3
                    # we will make the the learning rate is 0.5
                lr =1
                w[i]= w[i] -lr*dldw
                loss_w_dash= self.calc_loss(X,y,w)
                print(loss_w_dash - loss_w)
                loss_w = loss_w_dash
            
            if abs(loss_w) < 5:
                
                self.w = w
                
                return self.w
                print('converged to solution')
                
            else:
                print('not converged')
            
            

    def predict(self,X_new):
        predicted_y = X_new@self.w
        
        return predicted_y

In [814]:
lm = linear_model()

In [815]:
lm.train(X,y)

the true value =  [[7]
 [3]]
the predicted value =  [[13.]
 [12.]]
the total loss = -15.0
the true value =  [[7]
 [3]]
the predicted value =  [[13.]
 [12.]]
the total loss = -15.0
the true value =  [[7]
 [3]]
the predicted value =  [[11.]
 [ 9.]]
the total loss = -10.0
5.0
the true value =  [[7]
 [3]]
the predicted value =  [[11.]
 [ 9.]]
the total loss = -10.0
the true value =  [[7]
 [3]]
the predicted value =  [[10.]
 [10.]]
the total loss = -10.0
0.0
not converged
the true value =  [[7]
 [3]]
the predicted value =  [[10.]
 [10.]]
the total loss = -10.0
the true value =  [[7]
 [3]]
the predicted value =  [[8.]
 [7.]]
the total loss = -5.0
5.0
the true value =  [[7]
 [3]]
the predicted value =  [[8.]
 [7.]]
the total loss = -5.0
the true value =  [[7]
 [3]]
the predicted value =  [[7.]
 [8.]]
the total loss = -5.0
0.0
not converged
the true value =  [[7]
 [3]]
the predicted value =  [[7.]
 [8.]]
the total loss = -5.0
the true value =  [[7]
 [3]]
the predicted value =  [[5.]
 [5.]]
the

array([[2.],
       [0.]])

In [816]:
# even though this is not the correct value, but the tota loss is actually zero. I need to to solve this proble,

In [817]:
#n the issue of losses cancelling themselves are a direct result of not taking the sum of the absolute value , which is L1

In [818]:
# L1 loss

In [819]:
class linear_model:
    def __init__(self):
        pass
    
  
        
        return predicted_y

In [820]:
lm = linear_model()

In [821]:
lm.train(X,y)


[[2.50000000e+00]
 [1.77635684e-13]]
step 0
loss is now 7.512500000000001
step 1
loss is now 6.887499999999992
step 2
loss is now 6.262499999999983
step 3
loss is now 5.637499999999974
step 4
loss is now 5.0124999999999655
step 5
loss is now 4.387499999999957
step 6
loss is now 3.7624999999999473
step 7
loss is now 3.1374999999999384
step 8
loss is now 2.5124999999999296
step 9
loss is now 1.8874999999999207
step 10
loss is now 1.2624999999999114
step 11
loss is now 0.637499999999902
step 12
loss is now 0.012499999999893152
final w =  [[2.005]
 [3.005]]


array([[2.005],
       [3.005]])

# wa hoooooooooo :)

- The breakthrough was the fact hat I have to calculate dwdl once
- Also making the condition of stopping not zero but at 0.05
- And playing with the learning rate
- Of course also th earlier realization that I need to calucalte L1 and not just sum th loss since they were cancelling each other.

In [822]:
# Batch vs stochastic

while I was sleeping yesterday I was thinking about the calculation of gradients. More specifically I was thinking about how it is possible to calculate the gradient using one example, using some examples or all examples,or using all examples. The only difference will be in the way the loss is calculated. If only one example is included then we cacluate one loss, if n the the loss vectors, will have n rows each is associated with a loss, of course since we need only one number we will just take the mean of all losses. Note that we are calculatin the mean squared error using this methodology MAE. If we use L2. then we will be calculting the MSE.

In [823]:
# Using MSE

In [950]:
class linear_model:
    def __init__(self):
        pass
    
    def calc_loss(self,X,y,w, loss_measure = 'MSE'):
        
        
        """
        Calculating the loss or the deviation of the results we got from the model compared with the real values. The first step is to calculate the X@w which represents the results we got from
        the model. The second step is to evaulate the loss which can be done through a loss function that we define. for example here we define two ways to caculate the loss either using MAE, in
        which we first calculate the absolute difference between each predicted and true value and then we calucalte the mean. or using the MSW, in which we calculate the abolute difference between
        true and preidcted value, square it and then find the average. The loss we then be returned.
        
        """
        
       
        losses = []
        y_predicted = np.zeros(len(X))
        y_predicted = X@w
        
        if loss_measure == 'MSE':
            loss = (y - y_predicted)**2
        elif loss_measure == 'MAE':
            loss= abs(y - y_predicted)

        #print('the true value = ',y)
        #print('the predicted value = ',y_predicted)
        losses.append(loss)
        total_loss = np.mean(losses)
        #print('the total loss =', total_loss )
        return total_loss
      


    def train(self,X,y,loss_measure = 'MAE'):
        #w = np.ones([X.shape[1],1])
        np.random.seed(500)
        w = np.random.rand(X.shape[1],1)
        dldw = np.ones([X.shape[1],1])
        dldw[0] = 0.02
        dldw[1] = 0.02
        w[0] = 3
        w[1] = 3
        print(w)
        
    # calculate the derivitives, this happen once, that was my mistake, I was including it in the for loop.

        for i in range(len(w)):

            # f(w)

            loss_w = self.calc_loss(X,y,w,loss_measure = loss_measure)
            # we will choose the margin that we will accept as 0.5

            # f(w+h)

            h = 0.005
            w[i] = w[i] + h

            # dldw = f(w+h) - f(w)/h
            dldw[i] = (self.calc_loss(X,y,w,loss_measure = loss_measure) - loss_w)/h


        print(dldw)   
        
        # updating the weight
        
        lr =0.005
        
        for i in range(20):
            print('step',i)
            loss_w = self.calc_loss(X,y,w)
            print('loss is now',loss_w)
            if loss_w <= 0.08 :
                self.w = w
                print('final w = ',self.w)
                return self.w
            elif loss_w > 0.08 :
                w = w - lr*dldw
#         for i in range(10):
#             counter = counter + 1
            
#             print('loss = ',loss_w_dash)
#             #print(loss_w_dash - loss_w)
#             loss_w = loss_w_dash

#             

#                 return self.w
                
                

    def predict(self,X_new):
        predicted_y = X_new@self.w
        
        return predicted_y

In [951]:
lm = linear_model()
lm.train(X,y,loss_measure = 'MSE')

[[3.]
 [3.]]
[[13.0325]
 [-1.    ]]
step 0
loss is now 6.560162500000003
step 1
loss is now 5.7321160466406065
step 2
loss is now 4.9599711865624725
step 3
loss is now 4.243727919765584
step 4
loss is now 3.5833862462499555
step 5
loss is now 2.978946166015569
step 6
loss is now 2.4304076790624403
step 7
loss is now 1.9377707853905637
step 8
loss is now 1.501035484999939
step 9
loss is now 1.1202017778905646
step 10
loss is now 0.7952696640624431
step 11
loss is now 0.5262391435155735
step 12
loss is now 0.31311021624995605
step 13
loss is now 0.15588288226559058
step 14
loss is now 0.05455714156247709
final w =  [[2.092725]
 [3.075   ]]


array([[2.092725],
       [3.075   ]])

In [901]:
X_2d_new = np.array([[2,3],
                   [0,5]])

In [855]:
lm.predict(X_2d_new)

array([[13.845125],
       [16.15    ]])

In [828]:
# let's use the model we have trained for predicting the results for new data

In [ ]:
# The effect of initialzing weighhts with very smalll values. 

In [939]:
# ok, we know that dldw is basically how much the loss is affected when the weight is changed a little bit. Since the trajectory is not linear
# we expect that dldw is not constant. But I basically makes it so in the above code.

I think now I started to grasp the idea of foward pass and backward pass.
Where do we need the dldw, we need it when we want to update w. Now dldw is not constatnt because again , imagin that you are in this half-circle 
down. as you apprach the bottom the slopes acually goes dowm. I am going to do this for the above code.

In [1034]:
class linear_model:
    def __init__(self):
        pass
    
    def calc_loss(self,X,y,w, loss_measure = 'MSE'):
        
        
        """
        Calculating the loss or the deviation of the results we got from the model compared with the real values. The first step is to calculate the X@w which represents the results we got from
        the model. The second step is to evaulate the loss which can be done through a loss function that we define. for example here we define two ways to caculate the loss either using MAE, in
        which we first calculate the absolute difference between each predicted and true value and then we calucalte the mean. or using the MSW, in which we calculate the abolute difference between
        true and preidcted value, square it and then find the average. The loss we then be returned.
        
        """    
        losses = []
        y_predicted = np.zeros(len(X))
        y_predicted = X@w
        
        if loss_measure == 'MSE':
            loss = (y - y_predicted)**2
        elif loss_measure == 'MAE':
            loss= abs(y - y_predicted)

        #print('the true value = ',y)
        #print('the predicted value = ',y_predicted)
        losses.append(loss)
        total_loss = np.mean(losses)
        #print('the total loss =', total_loss )
        return total_loss
      

    def diff(self,w,X,y, loss_measure):
        """
        given a function f(x) and a point w, calculate th f'(x)
        
        """
        dldw = np.ones([X.shape[1],1])
        h = 0.005  
        for i in range(len(w)):
            print('i',i)

            # f(w)
            loss_w = self.calc_loss(X,y,w,loss_measure = loss_measure)
            # we will choose the margin that we will accept as 0.5
            # f(w+h)
            w[i] = w[i] + h      
            loss_w_plus_h = self.calc_loss(X,y,w,loss_measure = loss_measure)
            # dldw = f(w+h) - f(w)/h
            dldw[i] = (loss_w_plus_h- loss_w)/h
            
            print('dldw')
            print(dldw)
            
        return dldw  
        
     
    # calculate the derivitives, this happen once, that was my mistake, I was including it in the for loop.
    def train(self,X,y,loss_measure = 'MAE', lr = 0.07):
        """
        training of the model is done by evaluting loss and updating the weights
        """
        # initilization
        np.random.seed(50)
        w = np.random.rand(X.shape[1],1)
        # intialization. I am changing this manually
        #w[0] = 
        #w[1] = 3.5
        print(
        )
        print(w)    
        # updating the weight     
        #lr =0.07
        
        for i in range(20):
            print('step =',i)
            
            # forward pass is essentially the process of calculting the loss given the data and the weight, for the loss we need to calculate a predicted value
            # calculate the loss at the current weights
            loss_w = self.calc_loss(X,y,w)
            print('loss is now',loss_w)
            # stoping condition, note that we don't require the loss is to be exactly zero but close enough
            if loss_w <= 0.08 :
                self.w = w
                print('final w = ',self.w)
                return self.w
            
            # updating the weight. 
            elif loss_w > 0.08 :
                # the backpropagation is essentially the calculation of the partially derivives using chain rules. since we have only one layer at this time we will just calculate the dldw
                #First at that particular point we calculate dldw 
                dldw = self.diff(w,X,y,loss_measure)
                # Now we update the weight
                w = w -lr*dldw
                print('w')
                print(w)          
    def predict(self,X_new):
        predicted_y = X_new@self.w
        
        return predicted_y

In [1035]:
lm = linear_model()
lm.train(X,y,loss_measure = 'MSE', lr = 0.1)

[[0.49460165]
 [0.2280831 ]]
step = 0
loss is now 18.241141479081318
i 0
dldw
[[-16.76576171]
 [  1.        ]]
i 1
dldw
[[-16.76576171]
 [ -4.03843544]]
w
[[2.17617782]
 [0.63692665]]
step = 1
loss is now 6.202187820754634
i 0
dldw
[[4.68588497]
 [1.        ]]
i 1
dldw
[[ 4.68588497]
 [-4.90232452]]
w
[[1.71258932]
 [1.1321591 ]]
step = 2
loss is now 3.488924047704765
i 0
dldw
[[-1.83599794]
 [ 1.        ]]
i 1
dldw
[[-1.83599794]
 [-3.44827112]]
w
[[1.90118911]
 [1.48198621]]
step = 3
loss is now 2.217832915642432
i 0
dldw
[[0.26597227]
 [1.        ]]
i 1
dldw
[[ 0.26597227]
 [-2.93721669]]
w
[[1.87959189]
 [1.78070788]]
step = 4
loss is now 1.4340983468824953
i 0
dldw
[[-0.31351335]
 [ 1.        ]]
i 1
dldw
[[-0.31351335]
 [-2.31817612]]
w
[[1.91594322]
 [2.01752549]]
step = 5
loss is now 0.9285985368217826
i 0
dldw
[[-0.07776361]
 [ 1.        ]]
i 1
dldw
[[-0.07776361]
 [-1.88089223]]
w
[[1.92871958]
 [2.21061472]]
step = 6
loss is now 0.5998872488193161
i 0
dldw
[[-0.10476014]
 [ 1

array([[1.97789733],
       [2.74383692]])

- note that weight in the first dimention X[0] is being updated correctly, when I initialize with weight that is bigger than the correct once, the weight goes down, and when I initialize with 
a weight that is smaller than the correct weight then the weight will go up. But, for some reason there is almost no movement in the second dimention, X[1], the quetion is why ?I alreay tried initializing with a different set of values, but still there is no movements.


- I guess the solution deponds on how X1 and X2 affect f(x) and hence the loss funciton. It seems that if we change w a bit in X1 direction, the loss will be affected significantly, but if we 
change w in the X2 direction, then the loss will be affected that much hence the slow conversion to the correct values of w.