### Building Intuision about NN

In [146]:
import numpy as np

In [342]:
# The best approach to get an intuision for building NN is to start from scratch, and I will start with matrix mutiplication, as it's the foundational knowledge

let's start with equations, after all linear algebra was built to solve equations

X.w = y



In [344]:
# what does this eqaution tells us, that the dot product of feature matrix X and weight vector w will get us y. But the shape matters for matrix multiplication as we will see


In [147]:
# let's creat our feature matrix, we will have a data with only one example and 5 features.

In [346]:
X = np.array([10,12,5,3,-5]).reshape(1,5)
X


array([[10, 12,  5,  3, -5]])

we have come to know that there is a dependent variable y, that is linearly dependent on those features. That means if we take the right mix of theres features in X we will get y.
 of course the million dollar question is that what is the right mix. Let's say we the right mix of feature X1 is w1 and from featureX2 is w2 etc. Now, we will get the following equation

X1.w1 + X2.w2 + ...... Xn.wn = y

we can write the above equation in a compact form in the following form:

X.w = y

Now, to write this equation in the matrix form, we need to know the rules of matrix multiplication



- the rows of w has to be the same as the columns of X
- so if X shape is 1,5 then w needs to be 5x, so we can have any numbe of columns but the rows have to be 5. The resuled matrix will take the shape of (rows of X , columns of w)
- why is this important, well, since the number of rows in X is the numbe of example, observations in the data does not affect. We can have the same shape of w for any number of observations. 
- On the other hands, w is affected by the number of features, of course becuase each w is connected with aparticualr feature.
- Now when it comes the resulted y, of coursee we need one y for each observation, and therefore the numbe of rows in y is the same as number of observation. Now let's say we don't have one output
- I mean we have y1 and y2, we will face this in multi-classificaiton and also in NN when w have a layer with more than one unit. Here th columns of y will increase, and guess who will increase the numbe of columns to accomodate this, yes that's right. That's the NN

In [151]:
# ok, we need to learn about the dot product, so we can peformr X.w

In [152]:
# X is 5 * 1 and the output is 2 *1 so we need the w to be 2*5

w = np.array([
    [ 0.1, 0.1, 0.1,0.1,0.1],
    [0.1,0.1,0.1,0.1,0.1]

])

In [153]:
w = w.reshape(5,2)

In [154]:
w

array([[0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1],
       [0.1, 0.1]])

In [155]:
X@w

array([[1.5, 1.5]])

In [156]:
# input layer, 5 nodes        layer 1, 2 nodes

#
#                    #
#
#                    #
#

In [157]:
# let's make up a simple example to see if the NN can actually learn from examples


# y X1 + X2 + X3 + X4 + X5

# examples
X = np.array([[1,1,1,1,1],
             [2,1,2,2,2],
            [3,1,3,3,3],
            [3,2,3,3,3],
            [3,3,3,3,3],
            [3,4,3,3,3],
            [3,5,3,3,3],
            [3,6,3,3,3],
            [3,7,3,3,3],
            [3,8,3,3,3]
             ])


In [158]:
X.shape

(10, 5)

In [159]:
y = np.array([5,9,13,14,15,16,17,18,19,20])
y.shape

(10,)

### Train function

In [160]:
class linear_model:
    def __init__(self):
        pass

    def train(self,X,y):
        # create the weight vectorr
        w = np.ones([X.shape[1],1])
        losses = []
        y_predicted = np.zeros(len(X))
        for i in range(len(X)):
            y_predicted[i] = X[i]@w
            loss = y[i] - y_predicted[i]
            
            print('the true value = ',y[i])
            print('the predicted value = ',y_predicted[i])
            losses.append(loss)
        total_loss = np.sum(losses)
        print('the total loss =', total_loss )
        

In [161]:
lm = linear_model()

In [162]:
lm.train(X,y)

the true value =  5
the predicted value =  5.0
the true value =  9
the predicted value =  9.0
the true value =  13
the predicted value =  13.0
the true value =  14
the predicted value =  14.0
the true value =  15
the predicted value =  15.0
the true value =  16
the predicted value =  16.0
the true value =  17
the predicted value =  17.0
the true value =  18
the predicted value =  18.0
the true value =  19
the predicted value =  19.0
the true value =  20
the predicted value =  20.0
the total loss = 0.0


In [163]:
X[0]

array([1, 1, 1, 1, 1])

In [164]:
# note that we used the correct w for this case and hence we have loss of zero, let's change ws

In [165]:
class linear_model:
    def __init__(self):
        pass

    def train(self,X,y):
        w = np.ones([X.shape[1],1])
        w[0] = 0.2
        losses = []
        y_predicted = np.zeros(len(X))
        for i in range(len(X)):
            y_predicted[i] = X[i]@w
            loss_at_w = y[i] - y_predicted[i]
            loss_at_w_plus_h = y[i] - y_predicted[i]
            
            print('the true value = ',y[i])
            print('the predicted value = ',y_predicted[i])
            losses.append(loss_at_w )
        total_loss = np.sum(losses)
        print('the total loss =', total_loss)
              
        
        

In [166]:
lm = linear_model()

In [167]:
lm.train(X,y)

the true value =  5
the predicted value =  4.2
the true value =  9
the predicted value =  7.4
the true value =  13
the predicted value =  10.6
the true value =  14
the predicted value =  11.6
the true value =  15
the predicted value =  12.6
the true value =  16
the predicted value =  13.6
the true value =  17
the predicted value =  14.6
the true value =  18
the predicted value =  15.6
the true value =  19
the predicted value =  16.6
the true value =  20
the predicted value =  17.6
the total loss = 21.599999999999998


In [168]:
# as you can see here, the loss is no longer 0.

In [169]:
# it is obvious that we need to keep tweeking ws until we get the minium loss

### now comes the calculs part, first we know that we can write the loss as a function of ws

- L = f(w)
- dl/dw = f'(w) = (f(w+h) - f(w))/h

new_w = old+w - step_size* dl/dw

In [170]:
 #ok, I need to update w which is a vector of shape (x[1],1)
        # any change in w, for example if we change w[0], the vector y will change completely, not only y[0] as we dicussed before.
        # now as we said we want to change w by tweeking it a little bit, by adding dw, i.e adding a vector that will be similar in length to w
              
        # for example :
              # w = [1               df/dw = [0.10                                                        [1.2
              #      2                     0.04            > new w will be old_w _ step_size*dw.     >. 2.08         note that here we assumed step*size to be 2
               #     3]                    0.03]                                                         2.06
        
        # let's calculate dl/dw
        # but this will involve calculating the loss twice, one at and then at w + h
        # let's make a function of calculating the loss
        

## Using a simple model to solve the equation 3X = 6

In [171]:
class linear_model:
    def __init__(self):
        pass
    
    def calc_loss(self,X,y,w):
       
        losses = []
        y_predicted = np.zeros(len(X))
       
        
        y_predicted = X@w
        loss= y - y_predicted
            
        print('the true value = ',y)
        print('the predicted value = ',y_predicted)
        losses.append(loss)
        total_loss = np.sum(losses)
        print('the total loss =', total_loss )
        return total_loss
      


    def train(self,X,y):
        w = np.ones([X.shape[1],1])
        w[0] = 5
        
        for i in range(len(w)):
            loss_w = self.calc_loss(X,y,w)
            
            # the case when the loss is positive, in this case we need to decrease w
            
            # we will choose the margin that we will accept as 0.5
            
            if abs(loss_w)> 0:
                # since the equation is 3x =6 , then dw/dl = 3
                dldw = 3
            elif abs(loss_w)< 0:
                dldw = -3
                # we will make the the learning rate is 0.5
            lr =1
            w[0]= w[0] -lr*dldw
            loss_w_dash= self.calc_loss(X,y,w)
            print(loss_w_dash - loss_w)
            loss_w = loss_w_dash

            
            self.w = w
            print(self.w)
        
    def predict(self,X_new):
        predicted_y = X_new@self.w
        
        return predicted_y

In [172]:
X = np.array([3]).reshape(1,1)
y = np.array([6]).reshape(1,1)

In [173]:
X.shape

(1, 1)

In [174]:
w = np.ones([1,1])

In [175]:
X@w

array([[3.]])

In [176]:
lm = linear_model()

In [177]:
lm.train(X,y)

the true value =  [[6]]
the predicted value =  [[15.]]
the total loss = -9.0
the true value =  [[6]]
the predicted value =  [[6.]]
the total loss = 0.0
9.0
[[2.]]


In [178]:
# so essentially the equation we have is

# 2*X, this is our model, because this is basically what got us 6
# let's see what if we try a new X, say for example 4, we expect the new y to be 8

In [179]:
X_new = np.array([4])

In [180]:
y = lm.predict(X_new)

In [181]:
y

array([8.])

### let's now try equations for 2 variables


- X1 = 2
- X2 = 3

- 2X1 + X2 = 7
- 3X1 - X2 = 3

> this is the equivelant of having 2 examples


In [182]:
X = np.array([[2,1],
             [3,-1]])
X

array([[ 2,  1],
       [ 3, -1]])

In [183]:
y = np.array([7,3]).reshape(2,1)
y

array([[7],
       [3]])

In [250]:
class linear_model:
    def __init__(self):
        pass
    
    def calc_loss(self,X,y,w):
       
        losses = []
        y_predicted = np.zeros(len(X))
       
        
        y_predicted = X@w
        loss= y - y_predicted

        print('the true value = ',y)
        print('the predicted value = ',y_predicted)
        losses.append(loss)
        total_loss = np.sum(losses)
        print('the total loss =', total_loss )
        return total_loss
      


    def train(self,X,y):
        w = np.ones([X.shape[1],1])
        w[0] = 5
        w[1] = 3
        
        loss_w = self.calc_loss(X,y,w)
        while abs(loss_w) > 1:
            for i in range(len(w)):
                loss_w = self.calc_loss(X,y,w)

                # the case when the loss is positive, in this case we need to decrease w

                # we will choose the margin that we will accept as 0.5

                if abs(loss_w)> 0:
                    # since the equation is 3x =6 , then dw/dl = 3
                    dldw = 1
                elif abs(loss_w)< 0:
                    dldw = -3
                    # we will make the the learning rate is 0.5
                lr =1
                w[i]= w[i] -lr*dldw
                loss_w_dash= self.calc_loss(X,y,w)
                print(loss_w_dash - loss_w)
                loss_w = loss_w_dash
            
            if abs(loss_w) < 5:
                
                self.w = w
                
                return self.w
                print('converged to solution')
                
            else:
                print('not converged')
            
            

    def predict(self,X_new):
        predicted_y = X_new@self.w
        
        return predicted_y

In [190]:
lm = linear_model()

In [191]:
lm.train(X,y)

the true value =  [[7]
 [3]]
the predicted value =  [[13.]
 [12.]]
the total loss = -15.0
the true value =  [[7]
 [3]]
the predicted value =  [[13.]
 [12.]]
the total loss = -15.0
the true value =  [[7]
 [3]]
the predicted value =  [[11.]
 [ 9.]]
the total loss = -10.0
5.0
the true value =  [[7]
 [3]]
the predicted value =  [[11.]
 [ 9.]]
the total loss = -10.0
the true value =  [[7]
 [3]]
the predicted value =  [[10.]
 [10.]]
the total loss = -10.0
0.0
not vonverged
the true value =  [[7]
 [3]]
the predicted value =  [[10.]
 [10.]]
the total loss = -10.0
the true value =  [[7]
 [3]]
the predicted value =  [[8.]
 [7.]]
the total loss = -5.0
5.0
the true value =  [[7]
 [3]]
the predicted value =  [[8.]
 [7.]]
the total loss = -5.0
the true value =  [[7]
 [3]]
the predicted value =  [[7.]
 [8.]]
the total loss = -5.0
0.0
not vonverged
the true value =  [[7]
 [3]]
the predicted value =  [[7.]
 [8.]]
the total loss = -5.0
the true value =  [[7]
 [3]]
the predicted value =  [[5.]
 [5.]]
the

array([[2.],
       [0.]])

In [192]:
# even though this is not the correct value, but the tota loss is actually zero. I need to to solve this proble,

In [193]:
#n the issue of losses cancelling themselves are a direct result of not taking the sum of the absolute value , which is L1

In [194]:
# L1 loss

In [336]:
class linear_model:
    def __init__(self):
        pass
    
    def calc_loss(self,X,y,w):
        
        # just X@w matrix multiplicaion and then calculating the differrence from the real y and returning the absoute value.
       
        losses = []
        y_predicted = np.zeros(len(X))
       
        
        y_predicted = X@w
        loss= abs(y - y_predicted)

        #print('the true value = ',y)
        #print('the predicted value = ',y_predicted)
        losses.append(loss)
        total_loss = np.sum(losses)
        #print('the total loss =', total_loss )
        return total_loss
      


    def train(self,X,y):
        w = np.ones([X.shape[1],1])
        dldw = np.ones([X.shape[1],1])
        dldw[0] = 0.02
        dldw[1] = 0.02
        w[0] = 5
        w[1] = 3
        
    # calculate the derivitives, this happen once, that was my mistake, I was including it in the for loop.

        for i in range(len(w)):

            # f(w)

            loss_w = self.calc_loss(X,y,w)
            # we will choose the margin that we will accept as 0.5

            # f(w+h)

            h = 0.005
            w[i] = w[i] + h

            # dldw = f(w+h) - f(w)/h
            dldw[i] = (self.calc_loss(X,y,w) - loss_w)/h


        print(dldw)   
        
        # updating the weight
        
        lr =0.1
        
        for i in range(10):
            loss_w = self.calc_loss(X,y,w)
            print('loss is now',loss_w)
            if loss_w <= 0.05 :
                self.w = w
                print('final w = ',self.w)
            elif loss_w > 0.5 :
                w = w - lr*dldw
#         for i in range(10):
#             counter = counter + 1
            
#             print('loss = ',loss_w_dash)
#             #print(loss_w_dash - loss_w)
#             loss_w = loss_w_dash

#             

#                 return self.w
                
                

    def predict(self,X_new):
        predicted_y = X_new@self.w
        
        return predicted_y

In [337]:
lm = linear_model()

In [338]:
lm.train(X,y)


[[5.00000000e+00]
 [3.55271368e-13]]
loss is now 15.025000000000002
loss is now 12.524999999999967
loss is now 10.024999999999931
loss is now 7.524999999999895
loss is now 5.024999999999859
loss is now 2.5249999999998227
loss is now 0.024999999999786304
final w =  [[2.005]
 [3.005]]
loss is now 0.024999999999786304
final w =  [[2.005]
 [3.005]]
loss is now 0.024999999999786304
final w =  [[2.005]
 [3.005]]
loss is now 0.024999999999786304
final w =  [[2.005]
 [3.005]]


# wa hoooooooooo :)

- The breakthrough was the fact hat I have to calculate dwdl once
- Also making the condition of stopping not zero but at 0.05
- And playing with the learning rate
- Of course also th earlier realization that I need to calucalte L1 and not just sum th loss since they were cancelling each other.